export class PubContanst{
	//日志表类型
	static CHANGE_RECORD_TYPE_CONVERT="CONVERT";
	static CHANGE_RECORD_TYPE_GRANTING="GRANTING";

	/**
	 * 转产领用人签名
	 */
	static SIGNATURE_TYPE_CVT_RECEIVER="CVT_RECEIVER";
	/**
	 * 转产领用人签名-未下发情况
	 */
	static SIGNATURE_TYPE_CVT_RECEIVER_NO_GRANTING="CVT_RECEIVER_NO_GRANTING";


	//非安转产
	static CVT_NON_NOTICE_STATE_RECEIVED="RECEIVED";
	static CVT_NON_NOTICE_STATE_COMPLETED="COMPLETED";
	static CVT_NON_CHECK_STATE_SAVED="SAVED";

	static DICT_TYPE_USE_STATE=20;
	static DICT_TYPE_TECH_STATE=21;
	static DICT_TYPE_SECURITY_STATE=26;

}

